### ISSUE TITLE
Decorations on Windows are rendering multiple times

### ISSUE THREAD

**Issue by clearlysid** [clearlysid/tauri-plugin-decorum#22]
Under certain conditions the window controls are being rendered exactly 3 times. The example app in my repo doesn't have this issue, but my other apps do and so does a few more folks'.

![image](https://github.com/user-attachments/assets/50591d3d-f7da-4efb-9df7-7da41614c4e4)

**Comment by vonPB** [comment]
Having the same issue. React + Vite. Usually works after `ctrl + r` / refreshing the page one time. 
Also happens on production builds

Thanks for the plugin otherwise! Looks and works nicely

**Comment by kareemmahlees** [comment]
I would love for this plugin to land in my next release, but unfortunately, I am stuck with this issue.
I would love to help but I tried to reproduce the bug in a fresh new tauri app and it was fruitless.

**Comment by clearlysid** [comment]
@kareemmahlees what is the frontend framework you are using? I wonder if it is specific to React, since all my apps that are "problematic" as well as @vonPB's app uses React.

**Comment by kareemmahlees** [comment]
@clearlysid It's also React with tanstack router 👀

**Comment by kareemmahlees** [comment]
I just noticed something, previously I had a splash screen showing before the main window, after removing the splash screen the controls are now only doublets!

**Comment by vonPB** [comment]
Removing my splashscreen window resulted in only 1 control being rendered. Spamming refresh sometimes results in two controls showing up.

**Comment by trspro67** [comment]
I was able to consistently reproduce this issue. Created a debounce for controls creation and check if controls exist. 

https://github.com/clearlysid/tauri-plugin-decorum/pull/25

**Comment by clearlysid** [comment]
The latest version v1.1.0 should fix this. Thanks @trspro67 👏
