### ISSUE TITLE
(Windows only) "Restore" window functionality and icon

### ISSUE THREAD

**Issue by clearlysid** [clearlysid/tauri-plugin-decorum#5]
Horrible picture, but this guy 👇
<img width="146" alt="Screenshot 2024-05-13 at 8 53 11 AM" src="https://github.com/clearlysid/tauri-plugin-decorum/assets/30227512/6cdb64c9-947a-4b8d-b416-adad7f043fc5">

When a window is already maximized, the maximize icon should change to restore and clicking the button should return to whatever window size the window was before being maximized.

**Comment by yutotakano** [comment]
Haven't investigated too much, but could it be as simple as changing the click event handler to call win.unmaximize() if it is currently maximised?

**Comment by clearlysid** [comment]
@yutotakano I think you're right! Damn, I was worried I'd have to handle window positioning, state management etc. all by hand 😅 -- this will make the task a lot easier indeed!

**Comment by clearlysid** [comment]
PR #17 solves this 🚀
